### ISSUE TITLE
在发布文章时，提示发布成功，但文章列表一直刷新不出来

### ISSUE THREAD

**Issue by leo-joy** [AschPlatform/cctime#7]
在发布文章时，提示发布成功，但文章列表一直刷新不出来

**Comment by lbgod2222** [comment]
如果您是要在本地节点进行测试的话可以在根目录下的src/vuex/action.js  文件顶部的baseUrl变量内容需要替换 @leo-joy

**Comment by leo-joy** [comment]
之前已经替换为我自己的服务地址：let baseUrl = 'http://localhost:4096/api/dapps/ab6d04e9c3d5d09a9ce2753736e13fd46361a0a0abc6c3bf96eafe78536253a6' // 真实本地环境

**Comment by lbgod2222** [comment]
能把发布文章后的返回信息截图么？

**Comment by leo-joy** [comment]
![image](https://user-images.githubusercontent.com/6337643/35845119-d5949420-0b4b-11e8-9d7f-203659acb7e2.png)
![image](https://user-images.githubusercontent.com/6337643/35845135-eabf9aa2-0b4b-11e8-8b32-5d815d9d348e.png)

**Comment by lbgod2222** [comment]
![image](https://user-images.githubusercontent.com/20358402/35845161-14b2f340-0b4c-11e8-99a9-0ff062a51f68.png)
i wanna this

**Comment by leo-joy** [comment]
![image](https://user-images.githubusercontent.com/6337643/35845409-4fc54522-0b4d-11e8-8737-4851f370b53d.png)

**Comment by lbgod2222** [comment]
看样子是写入成功了，用下面的url，替换下关键数据，看是否有返回

http://testnet.cctime.org:4096/api/dapps/d352263c517195a8b612260971c7af869edca305bb64b471686323817e57b2c1/articles?sortBy=timestamp&limit=20&offset=0

**Comment by leo-joy** [comment]
![image](https://user-images.githubusercontent.com/6337643/35845928-6dddbaba-0b4f-11e8-9373-5f408ab691d6.png)

![image](https://user-images.githubusercontent.com/6337643/35845972-a1660ff4-0b4f-11e8-806d-c06b18426cfc.png)
前端没有问题，换了链接之后可以获取文章列表

**Comment by lbgod2222** [comment]
那就是本地服务的问题了，刚才给您的url您尝试过替换本地数据获取信息了么？会返回什么？

**Comment by leo-joy** [comment]
我本地数据库中，一条数据都没有，根本没有插入成功

**Comment by leo-joy** [comment]
![image](https://user-images.githubusercontent.com/6337643/35846155-5ac359fc-0b50-11e8-93d8-09f6ca7fa5d9.png)

**Comment by leo-joy** [comment]
我认为不是获取文章接口有问题，而是文章发布接口有问题，这个接口http://localhost:4096/api/dapps/ab6d04e9c3d5d09a9ce2753736e13fd46361a0a0abc6c3bf96eafe78536253a6/transactions/signed ，虽然提示成功，但数据根本没有插入的数据库中；
![image](https://user-images.githubusercontent.com/6337643/35847139-5038c1bc-0b54-11e8-8e43-980601737d3c.png)

**Comment by leo-joy** [comment]
但是我在cctime后端的代码中，怎么没有看到这个接口啊？ asch平台接口和具体应用的接口是怎么配合的？

**Comment by leo-joy** [comment]
我是把asch部署到docker中的，原先的版本是1.3.0，后升级到1.3.4后，这个问题就解决了
