### ISSUE TITLE
CCTime 后端功能迭代

### ISSUE THREAD

**Issue by CaosBad** [AschPlatform/cctime#8]
## 新增频道板块

让文章下沉一级，便于归类检索，也服务于英文版块需求

## 打赏奖励策略添加

添加押宝模式的结算算法，实现用户打赏行为的激励

- [x] 前期需求分析，数据库模型与打赏机制设计 `2018-02-27`
- [x] 技术方案评估审核 `2018-02-27`
- [x] 启动研发 `2018-02-28`
- [] 交付 ...

**Comment by 281468601** [comment]
3.26号上午开会，可以内部测试和还原UI界面图，这个任务就先先关闭了
